server:
  Port: :8000
  Mode: Development
  Timeout: 5
  CtxDefaultTimeout: 10

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

queues:
  - Name: queue0
    Length: 0
    SubscribersAmount: 0
  - Name: queue1
    Length: 1
    SubscribersAmount: 2
  - Name: queue2
    Length: 2
    SubscribersAmount: 2
  - Name: queue3
    Length: 3
    SubscribersAmount: 3
